### ISSUE TITLE
wan

### ISSUE THREAD

**Issue by molestt** [ShellGui/doc_comments#1]
# 应用`wan`留言区

**Comment by molestt** [comment]
留言1

**Comment by molestt** [comment]
留言2留言2留言2留言2留言2留言2留言2留言2留言2留言2留言2留言2留言2留言2留言2留言2留言2留言2留言2留言2留言2留言2留言2留言2留言2留言2留言2留言2留言2留言2留言2留言2留言2留言2留言2留言2留言2留言2

**Comment by molestt** [comment]
```js
function getIssue(title){
  var issue_id = apps.indexOf(title);
  var url = 'https://api.github.com/repos/ShellGui/doc_comments/issues/' + issue_id;
  $.get(url,function(data){
      makeIssue(data,title);
      getComments(data.number,title);
  },'json');
}
```

**Comment by molestt** [comment]
```css
.media {
  max-width: 100%;
  overflow: auto;
}
.comment-container {
	margin: 0;
	padding: 0;
	padding-bottom: 10px;
	border-bottom: 2px solid #666;
}
.comment-container li {
	margin: 0!important;
	border: none;
}
.comment-container .media-left img {
	min-width: 60px!important;
	min-height: 60px!important;
}
```
